forge 'http://forge.puppetlabs.com'

#
# Modules from the Puppet Forge
#

mod 'puppetlabs/stdlib',    '4.3.2'
mod 'puppetlabs/apt',       '1.6.0'
mod 'puppetlabs/ntp',       '3.2.1'
mod 'example42/puppi',      '2.1.10'
mod 'example42/timezone',   '2.0.11'

#
# Modules from Github
#

mod 'composer',             :git => 'https://github.com/andreas-weber/puppet-composer.git'
